version: "3"
services:
  db:
    image: postgres:14
    restart: 'always'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shednow-dev
    ports:
      - 5432:5432
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
    restart: "always"
    ports:
      - 5051:8080
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10

    environment:
      - ALLOW_EMPTY_PASSWORD=yes